//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBES.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_MapKey {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_MapKey() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NUBES.Properties.Resource_MapKey", typeof(Resource_MapKey).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   BizNo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BizNo {
            get {
                return ResourceManager.GetString("BizNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DateOfIssue과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DateOfIssue {
            get {
                return ResourceManager.GetString("DateOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DateOfSales과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DateOfSales {
            get {
                return ResourceManager.GetString("DateOfSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DocId과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DocId {
            get {
                return ResourceManager.GetString("DocId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nationality과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PassportNumber과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seq과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PurchaseSeq {
            get {
                return ResourceManager.GetString("PurchaseSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TotalCount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PurchaseTotalCnt {
            get {
                return ResourceManager.GetString("PurchaseTotalCnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ReceiptNo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiptNo {
            get {
                return ResourceManager.GetString("ReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RetailerName과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RetailerName {
            get {
                return ResourceManager.GetString("RetailerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SaleAmount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaleAmount {
            get {
                return ResourceManager.GetString("SaleAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TotalCharge과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TotalCharge {
            get {
                return ResourceManager.GetString("TotalCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TotalRefundAmount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TotalRefundAmount {
            get {
                return ResourceManager.GetString("TotalRefundAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TotalSaleAmount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TotalSaleAmount {
            get {
                return ResourceManager.GetString("TotalSaleAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TotalTaxAmount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TotalTaxAmount {
            get {
                return ResourceManager.GetString("TotalTaxAmount", resourceCulture);
            }
        }

        /// <summary>
        ///   RetailerAddr(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RetailerAddr
        {
            get
            {
                return ResourceManager.GetString("RetailerAddr", resourceCulture);
            }
        }


        /// <summary>
        ///   TokenDisplay(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TokenDisplay
        {
            get
            {
                return ResourceManager.GetString("TokenDisplay", resourceCulture);
            }
        }

        /// <summary>
        ///   TokenType(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TokenType
        {
            get
            {
                return ResourceManager.GetString("TokenType", resourceCulture);
            }
        }
    }
}
