//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBES.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_Print {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_Print() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NUBES.Properties.Resource_Print", typeof(Resource_Print).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Amount(SGD)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GLOBAL TAX FREE Pte.Ltd.
        ///541 Orchard Road #17-01 Liat Towers,
        ///Singapore 238881
        ///Tel : +65 6221 7058
        ///GST Reg. No. 201136344W과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CentralRefundAgency {
            get {
                return ResourceManager.GetString("CentralRefundAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date of Issue :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DateofIssue {
            get {
                return ResourceManager.GetString("DateofIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date of Sales :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DateofSales {
            get {
                return ResourceManager.GetString("DateofSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please keep this Ticket, the receipts and goods for Customs&apos; inspection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc01 {
            get {
                return ResourceManager.GetString("Desc01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Your personal data may be used for purposes of tax refunds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Desc02 {
            get {
                return ResourceManager.GetString("Desc02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doc-ID :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DocID {
            get {
                return ResourceManager.GetString("DocID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doc-Id과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DocID02 {
            get {
                return ResourceManager.GetString("DocID02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GST Amount :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GSTAmount {
            get {
                return ResourceManager.GetString("GSTAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GST Reg No :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GSTRegNo {
            get {
                return ResourceManager.GetString("GSTRegNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ELECTONIC TOURIST
        ///REFUND TICKET과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HeaderDesc {
            get {
                return ResourceManager.GetString("HeaderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   visit www.global-taxfree.com.sg과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string hompage {
            get {
                return ResourceManager.GetString("hompage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nationality :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Provisional Refund Amount :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProvisionalRefundAmount {
            get {
                return ResourceManager.GetString("ProvisionalRefundAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Provisional refund amounts are subject to eligibility check and approval.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PurchaseDesc {
            get {
                return ResourceManager.GetString("PurchaseDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receipt No.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiptNo {
            get {
                return ResourceManager.GetString("ReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retailer Name :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RetailerName {
            get {
                return ResourceManager.GetString("RetailerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sales Amount Incl GST :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SalesAmountInclGST {
            get {
                return ResourceManager.GetString("SalesAmountInclGST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Service Fee :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ServiceFee {
            get {
                return ResourceManager.GetString("ServiceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CENTRAL REFUND AGENCY과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_CentralRefundAgency {
            get {
                return ResourceManager.GetString("Title_CentralRefundAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DOC-ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_DocId {
            get {
                return ResourceManager.GetString("Title_DocId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IDENTIFIER과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Identifier {
            get {
                return ResourceManager.GetString("Title_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For more information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Information {
            get {
                return ResourceManager.GetString("Title_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PURCHASE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Purchase {
            get {
                return ResourceManager.GetString("Title_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RETAILER DETAILS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_RetailerDetails {
            get {
                return ResourceManager.GetString("Title_RetailerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TOURIST PASSPORT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_TouristPassport {
            get {
                return ResourceManager.GetString("Title_TouristPassport", resourceCulture);
            }
        }

        /// <summary>
        ///   Retailer Name :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Re_Print
        {
            get
            {
                return ResourceManager.GetString("Re_Print", resourceCulture);
            }
        }

        /// <summary>
        ///   Retailer Name :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Void_Print
        {
            get
            {
                return ResourceManager.GetString("Void_Print", resourceCulture);
            }
        }


        /// <summary>
        ///   Provisional refund amounts are subject to eligibility check and approval.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SINGAPORE
        {
            get
            {
                return ResourceManager.GetString("SINGAPORE", resourceCulture);
            }
        }

        /// <summary>
        ///   Date of Issue :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DocID03
        {
            get
            {
                return ResourceManager.GetString("DocID03", resourceCulture);
            }
        }

        /// <summary>
        ///   Provisional refund amounts are subject to eligibility check and approval.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_ETRS
        {
            get
            {
                return ResourceManager.GetString("Title_ETRS", resourceCulture);
            }
        }

        /// <summary>
        ///   Date of Issue :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DateTime
        {
            get
            {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Provisional refund amounts are subject to eligibility check and approval.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Central_desc
        {
            get
            {
                return ResourceManager.GetString("Central_desc", resourceCulture);
            }
        }

        /// <summary>
        ///   Date of Issue :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Global
        {
            get
            {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }

        /// <summary>
        ///   Date of Issue :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Taxfree
        {
            get
            {
                return ResourceManager.GetString("Taxfree", resourceCulture);
            }
        }

        /// <summary>
        ///   Provisional refund amounts are subject to eligibility check and approval.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_RetailerInfo
        {
            get
            {
                return ResourceManager.GetString("Title_RetailerInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Provisional refund amounts are subject to eligibility check and approval.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Merchant_name
        {
            get
            {
                return ResourceManager.GetString("Merchant_name", resourceCulture);
            }
        }

        /// <summary>
        ///   Provisional refund amounts are subject to eligibility check and approval.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Address
        {
            get
            {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }

        /// <summary>
        ///   Provisional refund amounts are subject to eligibility check and approval.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Touristinfo
        {
            get
            {
                return ResourceManager.GetString("Title_Touristinfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Provisional refund amounts are subject to eligibility check and approval.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Passport_no
        {
            get
            {
                return ResourceManager.GetString("Passport_no", resourceCulture);
            }
        }

        /// <summary>
        ///   Provisional refund amounts are subject to eligibility check and approval.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Token
        {
            get
            {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }

        /// <summary>
        ///   TOURIST PASSPORT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Credit
        {
            get
            {
                return ResourceManager.GetString("Title_Credit", resourceCulture);
            }
        }

        /// <summary>
        ///   TOURIST PASSPORT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Debit
        {
            get
            {
                return ResourceManager.GetString("Title_Debit", resourceCulture);
            }
        }

        /// <summary>
        ///   TOURIST PASSPORT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Other
        {
            get
            {
                return ResourceManager.GetString("Title_Other", resourceCulture);
            }
        }

        /// <summary>
        ///   Provisional refund amounts are subject to eligibility check and approval.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Purchase_date
        {
            get
            {
                return ResourceManager.GetString("Purchase_date", resourceCulture);
            }
        }

        /// <summary>
        ///   Provisional refund amounts are subject to eligibility check and approval.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Total_amt
        {
            get
            {
                return ResourceManager.GetString("Total_amt", resourceCulture);
            }
        }

        /// <summary>
        ///   Provisional refund amounts are subject to eligibility check and approval.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Information_foot
        {
            get
            {
                return ResourceManager.GetString("Information_foot", resourceCulture);
            }
        }


        /// <summary>
        ///   Provisional refund amounts are subject to eligibility check and approval.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Information_email
        {
            get
            {
                return ResourceManager.GetString("Information_email", resourceCulture);
            }
        }


        /// <summary>
        ///   Provisional refund amounts are subject to eligibility check and approval.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Information_qr
        {
            get
            {
                return ResourceManager.GetString("Information_qr", resourceCulture);
            }
        }

        /// <summary>
        ///   Date of Issue :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Information_qr1
        {
            get
            {
                return ResourceManager.GetString("Information_qr1", resourceCulture);
            }
        }
        /// <summary>
        ///   Date of Issue :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Information_qr_site
        {
            get
            {
                return ResourceManager.GetString("Information_qr_site", resourceCulture);
            }
        }
        /// <summary>
        ///   Date of Issue :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Information_qr2
        {
            get
            {
                return ResourceManager.GetString("Information_qr2", resourceCulture);
            }
        }

        /// <summary>
        ///   GLOBAL TAX FREE Pte.Ltd.
        ///541 Orchard Road #17-01 Liat Towers,
        ///Singapore 238881
        ///Tel : +65 6221 7058
        ///GST Reg. No. 201136344W과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Eservice_URL
        {
            get
            {
                return ResourceManager.GetString("Eservice_URL", resourceCulture);
            }
        }

        /// <summary>
        ///   GLOBAL TAX FREE Pte.Ltd.
        ///541 Orchard Road #17-01 Liat Towers,
        ///Singapore 238881
        ///Tel : +65 6221 7058
        ///GST Reg. No. 201136344W과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Email_addr
        {
            get
            {
                return ResourceManager.GetString("Email_addr", resourceCulture);
            }
        }

    }
}
